### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/goldfish#40]

**Comment by auzaheta** [comment]
I think we're in a good place for this now. Version 1.5.0 already fixed some warnings and notes. I will like to discuss how to solve the remaining ones here. Maybe @stadtfeldethz and @jhollway can follow the discussion on this.

A check run on the main branch using Windows and Fedora (Fedora Linux, R-devel, clang, gfortran) gives the following notes/warnings:

# Code/documentation and usage mismatches

```
* checking for code/documentation mismatches ... WARNING
Functions or methods with usage in documentation object 'goldfishEffects' but not in code:
  ‘indeg’ ‘outdeg’ ‘nodeTrans’ ‘ego’ ‘alter’ ‘tertius’ ‘tie’ ‘inertia’
  ‘recip’ ‘same’ ‘diff’ ‘sim’ ‘tertiusDiff’ ‘trans’ ‘cycle’ ‘clSender’
  ‘clReceiver’ ‘four’ ‘mixedTrans’ ‘mixedCycle’ ‘mixedClSender’
  ‘mixedClReceiver’
  
* checking Rd \usage sections ... WARNING
Objects in \usage without \alias in documentation object 'goldfishEffects':
  ‘indeg’ ‘outdeg’ ‘nodeTrans’ ‘ego’ ‘alter’ ‘tertius’ ‘tie’ ‘inertia’
  ‘recip’ ‘same’ ‘diff’ ‘sim’ ‘tertiusDiff’ ‘trans’ ‘cycle’ ‘clSender’
  ‘clReceiver’ ‘four’ ‘mixedTrans’ ‘mixedCycle’ ‘mixedClSender’
  ‘mixedClReceiver’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```
  
These two warnings are related to the same issue. I haven't found a clean and easy solution for this. 

I think a workaround is document the internal version of the effects functions on the package, i.e., `init_model_submodel.effectsX` and `update_model_submodel_effectX`. On the side, a vignette will work as the user documentation place where they can see the summary and how to use it in a friendly way. 

# Folder size note

```
* checking installed package size ... NOTE
  installed size is 15.1Mb
  sub-directories of 1Mb or more:
    libs   6.9Mb
```

After a quick check, I found that this is quite normal for packages using Rcpp, therefore not a problem for the submission. 

# Other advisable changes
Examples that take more than few seconds to run. I propose here to use a `\dontshow{}` to subset the events data frame to reduce time or even include the examples as `\dontrun{}`.  I do not have a real preference here.

**Comment by auzaheta** [comment]
@jhollway an update: for 1.5.2 on commit develop@d70869fd22d, a check on windows gives a warning about importing `migraph` and `broom` but not using them on the package.
On commit develop@83fccc6e698, I'm including those packages in the suggest field on the description file.

This commit also includes:

- solving some other warnings due to missing explicit imports declarations.
- changing the `aes` calls for `aes_string` calls to avoid warnings about No visible binding for global variable on the `ggplot2` plots calls.
- using `migraph` on vignettes. 
- cleaning vignettes enforcing `silent = TRUE` on the `estimate` function
- debugging examine functions when the time variable is already a numeric vector as on the social evolution example dataset.

**Comment by jhollway** [comment]
`{goldfish}` is now [available on CRAN](https://cran.r-project.org/web/checks/check_results_goldfish.html)!
